### ISSUE TITLE
DrugBank PMIDs do not have colons in the CURIE prefix

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1271]
see issue #1269 where the problem is described

**Comment by kvarforl** [comment]
Did this get fixed in this commit ? https://github.com/RTXteam/RTX/commit/5542964ce5041aac5e92bd6467da37beb4666fed

**Comment by saramsey** [comment]
Hi @kvarforl, yes, you are right!  I was (as usual) kind of scatterbrained and checked in what I hope is a fix, and then forgot to do anything else about it. If it looks good to you, please mark this issue as "verify-in-next-kg2-build".  Thank you!

**Comment by ericawood** [comment]
Verifying this in KG2.5.2 now

**Comment by ericawood** [comment]
This is not yet fixed, per KG2.5.2:
```
{
  "iri": "https://identifiers.org/drugbank:DB00546",
  "category_label": "drug",
  "deprecated": "False",
  "description": "Adinazolam (Deracyn®) is a benzodiazepine derivative with anxiolytic, anticonvulsant, sedative, and antidepressant properties. Adinazolam was first developed to enhance the antidepressant effects of [alprazolam]. It has never been approved by the FDA for clinical use.",
  "creation_date": "2005-06-13",
  "update_date": "2020-04-02",
  "synonym": [
    "8-Chloro-1-((dimethylamino)methyl)-6-phenyl-4H-s-triazolo(4,3-a)(1,4)benzodiazepine",
    "Adinazolam",
    "Adinazolamum"
  ],
  "full_name": "Adinazolam",
  "name": "Adinazolam",
  "provided_by": "identifiers_org_registry:drugbank",
  "id": "DRUGBANK:DB00546",
  "category": "biolink:Drug",
  "publications": [
    "PMID6320036",
    "PMID6148400",
    "PMID2867497"
  ]
}
```

**Comment by ericawood** [comment]
Actually, due to an error with #1267, this issue still needs to be verified.

**Comment by ericawood** [comment]
This is fixed in KG2.5.2:
```
{
  "iri": "https://identifiers.org/drugbank:DB04581",
  "category_label": "chemical_substance",
  "full_name": "1-benzylimidazole",
  "deprecated": "False",
  "name": "1-benzylimidazole",
  "description": "1-benzylimidazole, an N-imidazole derivative, has been shown to have strong cardiotonic activity.",
  "provided_by": "identifiers_org_registry:drugbank",
  "creation_date": "2007-09-11",
  "id": "DRUGBANK:DB04581",
  "category": "biolink:ChemicalSubstance",
  "update_date": "2020-03-01",
  "publications": [
    "PMID:7684507",
    "PMID:6142461",
    "PMID:1159635"
  ]
}
```
