### ISSUE TITLE
COHD query takes a long time?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1667]
I was working with Jenn and Ryan on workflow C and came across a problem where COHD seemed to be taking a long time. Here's the query:
```
{
  "edges": {
    "e00": {
      "constraints": [],
      "object": "n00",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n01"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0005301"
      ],
      "is_set": false
    }
  }
}
```

In the logs:
```
2021-09-21T22:21:09.227719 INFO: Getting the OMOP id for n01
2021-09-21T22:26:56.018523 INFO: COHD: Query for edge e00 completed (e00: 276, n00: 276, n01: 1)
```

There's an almost 6-minute gap between these two lines, which is really dragging ARAX down, since other queries complete or timeout within 30 seconds.

Is this surprising? fixable? inevitable?

should we be applying a 30 second timeout to local KPs like COHD just like we do to web-based KP queries?

**Comment by amykglen** [comment]
interestingly, when you set `COHD_slow_mode=true`, which makes it so that `TRAPIQuerier` is used for COHD instead of `COHDQuerier`, it looks like the COHD TRAPI API returns 200+ answers for this query in about 3 seconds:
```
add_qnode(ids=MONDO:0005301, key=n0)
add_qnode(categories=biolink:SmallMolecule, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:correlated_with)
expand(kp=COHD, COHD_slow_mode=true)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
that is quite fast.

(though after that it produces an error in TRAPIQuerier that I just fixed in `master` - was because their answer KG includes a few edges that don't have any bindings to the QG)

could we just use the COHD TRAPI API? (so, use `TRAPIQuerier` for COHD)? seems like maybe they've sped up their API.

then COHD queries would be run using Expand's standard asynchronous methods, which would further speed things up overall.

**Comment by chunyuma** [comment]
Hello @edeutsch, I realize this problem recently and it seems like this is a trade-off. If we want ARAX returns as many number of results as COHD api returns, we have to call their api but that might lead to slow query. But if we use our local database to map the OMOP ids, it might be not accurate. I'm wondering if we can contact COHD team to let them provide us their OMOP mapping list so that we can store them in our local database.

**Comment by amykglen** [comment]
great - I just did some more testing and when using their TRAPI API, every query I've checked returns results in about 15 seconds, which is plenty fast! all 4 of our COHD expand pytests complete in a combined 1 minute, whereas without using TRAPIQuerier they take 15+ minutes. 

this seems like a great solution because we're of course getting all of their answers (eliminates the OMOP mapping problem) yet it's essentially as fast as our local COHDQuerier used to be before the change to the slower OMOP mapping method. 

any objections to me changing this in Expand? (to switch to `TRAPIQuerier` for COHD)

**Comment by chunyuma** [comment]
Ah, interesting. This might indicate that they speed up their API. Then I agree to switch it to `TRAPIQuerier` with two advantages:
1. eliminates the OMOP mapping problem
2. we don't need to rebuild the COHD database each time when we update our KG2 version.

Thanks @amykglen for these testing!

**Comment by rtroper** [comment]
I was going to open a separate bug report, but this seems to be part of the same issue. If @amykglen's fix doesn't resolve the following issue, then perhaps we can open a separate bug report. I started with essentially the same query as Eric's above, but using `has_real_world_evidence_of_association_with` as the predicate and submitted to ARAX:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n00": {
                    "ids": [
                        "MONDO:0005301"
                    ],
                    "is_set": false,
                    "constraints": []
                },
                "n01": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ],
                    "is_set": false,
                    "constraints": []
                }
            },
            "edges": {
                "e00": {
                    "predicates": [
                        "biolink:has_real_world_evidence_of_association_with"
                    ],
                    "subject": "n00",
                    "object": "n01",
                    "constraints": [],
                    "exclude": false
                }
            }
        }
    }
}
```

It stalls at 44% for a while (presumably for the reason that Amy noted).

![image](https://user-images.githubusercontent.com/18222763/134266638-3dce9979-4f92-4821-ac85-5b143a527ce2.png)

Eventually, it finishes, but we're notified that COHD successfully returned results after 372 seconds, but that the clinical risk KP timed out after 30 seconds.

![image](https://user-images.githubusercontent.com/18222763/134266744-da4c23aa-4eb6-4685-a516-2a0954e5a489.png)

I tested the query directly on the clinical risk KP endpoint and got results back. I then tested the query through the ARS (https://arax.ncats.io/?source=ARS&id=9c98e4f7-7e8c-49dc-808e-2bd7ad0324d7). I got the expected results from the clinical risk KP via BTE, but ARAX shows a 598 error.

![image](https://user-images.githubusercontent.com/18222763/134266829-c10a55c5-406e-48a0-b50c-e6d4e36503d6.png)

**Comment by amykglen** [comment]
ok, the switch to TRAPIQuerier for COHD is in `master`. will verify it's working on production after the next rollout.

**Comment by edeutsch** [comment]
Great, thanks. arax.ncats.io is undergoing surgery by Dr. Womack at the moment. Will be back up again soon.

**Comment by edeutsch** [comment]
Surgery was successful and the patient is in recovery!

The latest master is now rolled out to all deployments:
```
 code/ARAX/ARAXQuery/ARAX_expander.py           |  13 +--
 code/ARAX/ARAXQuery/Expand/expand_utilities.py |  51 +---------
 code/ARAX/ARAXQuery/Expand/trapi_querier.py    |  40 ++++----
 code/ARAX/Documentation/DSL_Documentation.md   | 420 ++++++++++++++++++++++++++++++++++-----------------------------------------------
 code/ARAX/test/test_ARAX_expand.py             |  63 ++-----------
 code/ARAX/test/test_ARAX_standup_queries.py    |   1 +
 code/ARAX/test/test_ARAX_workflows.py          |   2 +-
```

The query at the top appears to operate as designed now.

closing, thanks.

**Comment by rtroper** [comment]
An update on the timeout issue I was running into. It appears that BTE and clinical risk KP are on the cusp of the timeout limit (30 seconds), so I don't always see results for both of them for this query. I tried it a moment ago and clinical risk KP made it in time (21 seconds), but BTE did not.

When I try the query directly on the clinical risk KP endpoint (https://api.bte.ncats.io/v1/smartapi/d86a24f6027ffe778f84ba10a7a1861a/query) or the BTE endpoint (https://api.bte.ncats.io/v1/query), results come back within about 5 seconds. However, I noticed in the status description for the ARAX query that, after the curie synonymization, ARAX comes up with 18 curies that it submits as a batch. I wonder if this is what's making it take longer than a direct query (with a single curie) on the BTE and clinical risk KP endpoints.

I believe @edeutsch mentioned that 30 seconds was an agreed-upon (in Translator) timeout limit, so I didn't submit a separate "bug" report since this technically seems to be working as-designed. It would be great, tough, if this timeout limit could be extended to a minute.

![image](https://user-images.githubusercontent.com/18222763/134383626-a0a07b51-9fb2-43b2-8e88-4be5dff7161b.png)
