### ISSUE TITLE
Port to KGNodeIndex

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#170]
Use Eric's KGNodeIndex instead of a bunch of dicts in ``Question.py``.

- [x] Test ``KGNodeIndex.py``
- [x] compare timing with current solution
- [x] implement in ``Question.py``
- [x] test

**Comment by dkoslicki** [comment]
Note: when updating to a new KG, we'll need to re-run ``/KGMetadata/dumpdata.py`` and then rebuild the ``KGNodeIndex.py`` SQLite database.

**Comment by dkoslicki** [comment]
KGNodeIndex code timing: ave. of 5.6 seconds per question
Old code timing: 2.8 seconds per question
@edeutsch Are there any fancy speed improvements we can make to the SQLite database that will speed up ``get_curies``? This new code (while more robust) is 2X slower than the old code. It's probably due to the following: when looking for KG node names, I need to look at every block (of every length, starting with the largest block size) of the input text and break when we get a hit since we don't know a-priori if the bioentity name contains spaces or not. So for a sentence of the form: "what diseases are similar to cerebral malaria", it calls ``get_curies`` on each item in the list:
```python
["what diseases are similar to cerebral malaria", "what diseases are similar to cerebral", "diseases are similar to cerebral malaria", "what diseases are similar to", "diseases are similar to cerebral", "are similar to cerebral", ... ,"malaria"]
```

**Comment by dkoslicki** [comment]
@edeutsch When/where should I be using the ``disconnect`` method in ``KGNodeIndex``? I'm currently getting the following after the code completes successfully:
```python
Exception ignored in: <bound method KGNodeIndex.__del__ of <KGNodeIndex.KGNodeIndex object at 0x7fd80d293eb8>>
Traceback (most recent call last):
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/KGNodeIndex.py", line 34, in __del__
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/KGNodeIndex.py", line 94, in disconnect
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1922, in dispose
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1296, in recreate
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/pool.py", line 265, in __init__
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/event/base.py", line 142, in _update
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 347, in _update
  File "/home/dkoslicki/Dropbox/Repositories/RTX/VE3/lib/python3.5/site-packages/sqlalchemy/event/registry.py", line 113, in _stored_in_collection_multi
KeyError: (<weakref at 0x7fd80e834b88; to 'function' at 0x7fd7e8b10510 (go)>,)
```
(at least, that's what figure is the cause of the error)

**Comment by dkoslicki** [comment]
@edeutsch In particular, running this simple script results in the above error:
```python
import timeit
t0 = timeit.default_timer()
import ParseQuestion
p = ParseQuestion.ParseQuestion()
for i in range(0, 10):
	res = p.parse_question("What biological processes involve proteins target by naproxen")
t1 = timeit.default_timer()
print(t1-t0)
```

**Comment by edeutsch** [comment]
Just getting in to look at this now....

**Comment by edeutsch** [comment]
okay, I just pushed a version that's faster. I had a bit trouble because I made all my changes and then realized that you had edited the file, too. merging was awkward but I think I did it right. you may want to check to see if I broke something you did.

Regarding the disconnect crash, I'm not sure I understand what's going on and I need to step away for a sec. The short answer to your questions is DON'T call disconnect() it should be automatic when the object is destroyed. Just like in main(). No disconnecting. Does that help?

**Comment by edeutsch** [comment]
I poodled around a little trying to figure out the disconnect crash, but I don't understand it. Maybe it's related to it being a global in Question.py? I tried a bunch of things and nothing seemed to work or make sense. So I just commented out the call to disconnect() on destruct and there's no more error. Shouldn't harm anything although seems untidy. I wouldn't worry about it any more.

**Comment by edeutsch** [comment]
(oh, and you'll need to rebuild the database for the changes to work)

**Comment by dkoslicki** [comment]
Yeah, this is great! Timing down to ~2.4 seconds per question (still not the best, but at least slightly faster than the old code, and a lot more robust). The error has disappeared now too!

**Comment by edeutsch** [comment]
are you saying that the actual finding curies is 2.4 seconds or the whole question is? I'm seeing about 0.001 seconds per lookup on rtx, so for 2.4 seconds, that would be 2400 lookups. Are you really doing that many lookups? that would seem like a good place for optimization.

**Comment by edeutsch** [comment]
for example, how fast does the main() in the class run? I see 15 queries in 0.018 seconds. not fast enough?

**Comment by dkoslicki** [comment]
@edeutsch is porting to SQL to circumvent SQLite not being thread safe. Will close this issue after he's finished creating fallback to SQLite for local testing purposes.

**Comment by edeutsch** [comment]
except that this is bug that I will fix. should not be necessary

**Comment by dkoslicki** [comment]
Closing this as it's basically finished, sans the bug that @edeutsch mentioned (needing to create KGNodeIndex in every location it's run). See also the bug in #203
