### ISSUE TITLE
RTX-KG2 is returning subclasses without the appropriate `query_id`

### ISSUE THREAD

**Issue by maximusunc** [RTXteam/RTX#2209]
I am sending this query:
```json
{
  "workflow": [
    {
      "id": "lookup"
    }
  ],
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["MONDO:0004979"],
          "categories": ["biolink:Disease"],
          "is_set": false,
          "constraints": []
        },
        "n2": {
          "ids": null,
          "categories": ["biolink:Gene", "biolink:Protein"],
          "is_set": false,
          "constraints": []
        }
      },
      "edges": {
        "e3": {
          "subject": "n2",
          "object": "n0",
          "knowledge_type": null,
          "predicates": [
            "biolink:contributes_to",
            "biolink:associated_with",
            "biolink:gene_associated_with_condition"
          ],
          "attribute_constraints": [],
          "qualifier_constraints": []
        }
      }
    }
  }
}
```
to https://arax.ncats.io/beta/api/rtxkg2/v1.4/query and I'm receiving some results like:
```json
{
        "analyses": [
          {
            "edge_bindings": {
              "e3": [
                {
                  "id": "45522576"
                },
                {
                  "id": "44710546"
                }
              ]
            },
            "resource_id": "infores:rtx-kg2"
          }
        ],
        "description": "No description available",
        "essence": "PIK3CD",
        "essence_category": "['biolink:Gene', 'biolink:Protein']",
        "node_bindings": {
          "n0": [
            {
              "id": "MONDO:0004979"
            }
          ],
          "n2": [
            {
              "id": "NCBIGene:5293"
            }
          ]
        },
        "resource_id": "infores:arax"
      }
```
but I'm also getting results like:
```json
{
        "analyses": [
          {
            "edge_bindings": {
              "e3": [
                {
                  "id": "44886886"
                }
              ]
            },
            "resource_id": "infores:rtx-kg2"
          }
        ],
        "description": "No description available",
        "essence": "IL31RA",
        "essence_category": "['biolink:Gene', 'biolink:Protein']",
        "node_bindings": {
          "n0": [
            {
              "id": "DOID:0080809"
            }
          ],
          "n2": [
            {
              "id": "NCBIGene:133396"
            }
          ]
        },
        "resource_id": "infores:arax"
      }
```
MONDO:0004979 is asthma, and DOID:0080809 is chronic asthma, which is a subclass of what I asked for. According to the TRAPI 1.4.0 spec right now, a `query_id` of MONDO:0004979 needs to be included in the corresponding node_bindings to link the subclass with the original query_graph curie.

**Comment by amykglen** [comment]
ok, this has been fixed/tested in `master` - I'll verify it's working as expected after the next deployment to our dev instances

**Comment by maximusunc** [comment]
You're responding with 340 results for that query, and it looks like 128 of them are subclasses that don't match what was sent with no `query_id`

**Comment by amykglen** [comment]
@maximusunc - that's very strange - I'm seeing a different result set than you're reporting when I run that latest example query you provided ([here](https://github.com/RTXteam/RTX/issues/2209#issuecomment-1845857257)) against the same endpoint (kg2 beta). there are 212 results, and there is no result for NCBIGene:7442. is it possible request caching was at play on your end?

**Comment by maximusunc** [comment]
Apologies, I think your service is doing the right thing now, and we still have a lingering bug somewhere on our end. Thanks Amy!

**Comment by amykglen** [comment]
Ok cool, no worries. Thanks for reporting!
