### ISSUE TITLE
UMLS Metathesaurus has a lot of concepts with two or more TUIs; map each to a single Biolink category where possible

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#762]

**Comment by saramsey** [comment]
Strategy:
1. Grep the logfile for warnings related to "multiple TUI" mappings for UMLS concepts
2. Identify the most common TUI-TUI pairs that co-occur
3. For each of those most common pairs, think about how to map unambiguously to Biolink categories
4. Modify `multi_owl_to_json_kg.py` so that it knows (and applies) the mappings from step (3) above, perhaps using a YAML file or some such

**Comment by saramsey** [comment]
From analyzing the `build-kg2-test.log`:
```
grep 'has CUI with multiple associated TUIs:' build-kg2-test.log  | cut -f3 -d\: | sort | uniq -c | sort -k1 -nr
```
we get:
```
   4732  T109, T121
   3980  T116, T126
   2485  T123, T116
   1903  T116, T123
    930  T121, T109
    669  T116, T192
    577  T116, T129
    516  T129, T121
    454  T129, T116
    283  T121, T116
    246  T121, T197
    221  T073, T093
    216  T130, T109
    201  T109, T195
    180  T116, T121
    171  T114, T123
    162  T192, T116
    155  T109, T123
    147  T123, T114
    143  T129, T121, T116
    140  T109, T125, T121
    132  T109, T131
    122  T116, T129, T121
    118  T109, T127, T121
     97  T125, T121, T116
     87  T116, T126, T192
     83  T121, T114
     81  T121, T129
     80  T121, T116, T126
     79  T109, T130
     70  T019, T047
     69  T116, T125, T121
     68  T116, T192, T129
     68  T114, T121
     65  T126, T116
     64  T109, T123, T121
     57  T123, T121, T116
     56  T125, T116
     55  T109, T121, T131
     54  T116, T126, T121
     51  T116, T123, T121
     49  T195, T109
     47  T116, T125
     43  T131, T109
     41  T122, T109
     39  T129, T116, T192
     36  T121, T116, T129
     31  T127, T121
     31  T109, T122
     29  T109, T129, T121
     27  T195, T116
     27  T123, T121
     26  T073, T170
     25  T192, T129, T116
     24  T109, T125
     21  T130, T109, T121
     21  T109, T129
     20  T109, T121, T130
     19  T123, T109
     18  T200, T203
     18  T125, T121
     17  T196, T121
     17  T116, T126, T129
     16  T116, T195
     15  T123, T121, T109
     14  T197, T130
     14  T192, T116, T126
     14  T121, T116, T125
     13  T130, T121, T197
     13  T121, T196
     13  T092, T073
     12  T168, T109
     12  T123, T196
     12  T121, T109, T127
     11  T197, T122
     11  T130, T129, T121
     10  T130, T197
     10  T130, T129
     10  T129, T116, T126
     10  T121, T197, T130
      9  T131, T197
      9  T131, T116
      9  T130, T196
      9  T125, T121, T109
      9  T123, T131, T116
      9  T109, T168
      8  T196, T131
      8  T196, T130
      8  T196, T123
      8  T123, T131
      8  T123, T121, T196
      8  T122, T197
      8  T109, T127
      8  T059, T063
      7  T197, T131
      7  T127, T121, T109
      7  T123, T121, T114
      7  T121, T130, T109
      7  T116, T130, T129
      7  T116, T130
      7  T093, T073
      7  T047, T019
      6  T203, T200
      6  T196, T123, T121
      6  T130, T121
      6  T129, T130
      6  T123, T121, T197
      6  T121, T131, T109
      6  T121, T130
      6  T047, T190
      5  T130, T129, T116
      5  T129, T116, T130
      5  T121, T131
      5  T120, T109
      5  T025, T121
      4  T197, T121
      4  T129, T121, T130
      4  T121, T197, T131
      4  T121, T109, T125
      4  T116, T126, T130
      4  T116, T123, T131
      4  T116, T121, T131
      4  T116, T114, T123
      4  T109, T121, T168
      3  T196, T130, T121
      3  T170, T060
      3  T168, T109, T121
      3  T131, T196
      3  T130, T109, T131
      3  T123, T197
      3  T121, T131, T116
      3  T121, T127
      3  T121, T109, T129
      3  T114, T130
      3  T109, T123, T131
      2  T190, T047
      2  T131, T130, T109
      2  T131, T116, T126
      2  T127, T121, T116
      2  T126, T121, T116
      2  T123, T116, T114
      2  T121, T196, T130
      2  T121, T131, T197
      2  T121, T116, T123
      2  T121, T025
      2  T116, T130, T129, T121
      2  T116, T122
      2  T114, T123, T121
      2  T109, T131, T130
      2  T104, T122
      2  T073, T092
      2  T062, T060
      2  T050, T191
      1  T197, T196
      1  T196, T131, T197
      1  T196, T121, T131
      1  T196, T109
      1  T195, T130, T109
      1  T195, T114
      1  T192, T109
      1  T170, T062
      1  T131, T129
      1  T130, T197, T131
      1  T130, T196, T121
      1  T130, T123, T114
      1  T130, T116
      1  T129, T131, T116
      1  T129, T121, T131
      1  T129, T121, T116, T130
      1  T129, T121, T109
      1  T129, T109
      1  T127, T121, T114
      1  T127, T114
      1  T127, T109
      1  T125, T116, T130
      1  T125, T109
      1  T123, T116, T130
      1  T122, T130
      1  T121, T130, T196
      1  T121, T125
      1  T121, T116, T130, T129
      1  T121, T116, T130
      1  T121, T116, T114
      1  T121, T109, T123
      1  T116, T131
      1  T116, T130, T125
      1  T116, T127, T121
      1  T116, T126, T131
      1  T116, T126, T114
      1  T116, T114
      1  T114, T130, T123
      1  T114, T129
      1  T114, T028
      1  T109, T195, T130
      1  T109, T129, T130
      1  T109, T123, T130
      1  T109, T120
      1  T104, T121
      1  T065, T170
      1  T065, T066
      1  T060, T170
      1  T057, T066
      1  T028, T114
```

**Comment by ericawood** [comment]
**Some reconstruction of the data above**

Frequency of each TUI grouping such that duplicate orderings (eg. T109, T121 vs T121, T109) are together in a sorted list:
```
['T109', 'T121'] : 5662
['T116', 'T123'] : 4388
['T116', 'T126'] : 4045
['T116', 'T129'] : 1031
['T116', 'T192'] : 831
['T121', 'T129'] : 597
['T116', 'T121'] : 463
['T114', 'T123'] : 318
['T116', 'T121', 'T129'] : 301
['T109', 'T130'] : 295
['T121', 'T197'] : 250
['T109', 'T195'] : 250
['T073', 'T093'] : 228
['T116', 'T121', 'T125'] : 180
['T109', 'T131'] : 175
['T109', 'T123'] : 174
['T109', 'T121', 'T125'] : 153
['T114', 'T121'] : 151
['T109', 'T121', 'T127'] : 137
['T116', 'T121', 'T126'] : 136
['T116', 'T129', 'T192'] : 132
['T116', 'T121', 'T123'] : 110
['T116', 'T125'] : 103
['T116', 'T126', 'T192'] : 101
['T109', 'T121', 'T123'] : 80
['T019', 'T047'] : 77
['T109', 'T122'] : 72
['T109', 'T121', 'T131'] : 61
['T109', 'T121', 'T130'] : 48
['T116', 'T195'] : 43
['T121', 'T127'] : 34
['T109', 'T121', 'T129'] : 33
['T121', 'T196'] : 30
['T116', 'T126', 'T129'] : 27
['T121', 'T123'] : 27
['T073', 'T170'] : 26
['T109', 'T125'] : 25
['T130', 'T197'] : 24
['T200', 'T203'] : 24
['T121', 'T130', 'T197'] : 23
['T109', 'T129'] : 22
['T109', 'T168'] : 21
['T123', 'T196'] : 20
['T122', 'T197'] : 19
['T121', 'T125'] : 19
['T130', 'T196'] : 17
['T116', 'T129', 'T130'] : 17
['T131', 'T197'] : 16
['T129', 'T130'] : 16
['T121', 'T129', 'T130'] : 15
['T073', 'T092'] : 15
['T121', 'T123', 'T196'] : 14
['T116', 'T123', 'T131'] : 13
['T121', 'T130'] : 12
['T131', 'T196'] : 11
['T116', 'T131'] : 10
['T109', 'T127'] : 9
['T114', 'T121', 'T123'] : 9
['T116', 'T130'] : 8
['T047', 'T190'] : 8
['T059', 'T063'] : 8
['T123', 'T131'] : 8
['T109', 'T130', 'T131'] : 7
['T116', 'T121', 'T131'] : 7
['T121', 'T130', 'T196'] : 7
['T109', 'T121', 'T168'] : 7
['T025', 'T121'] : 7
['T114', 'T116', 'T123'] : 6
['T121', 'T123', 'T197'] : 6
['T121', 'T131', 'T197'] : 6
['T109', 'T120'] : 6
['T121', 'T131'] : 5
['T116', 'T121', 'T129', 'T130'] : 4
['T116', 'T126', 'T130'] : 4
['T060', 'T170'] : 4
['T116', 'T126', 'T131'] : 3
['T114', 'T130'] : 3
['T109', 'T123', 'T131'] : 3
['T116', 'T121', 'T127'] : 3
['T123', 'T197'] : 3
['T116', 'T125', 'T130'] : 2
['T109', 'T130', 'T195'] : 2
['T114', 'T123', 'T130'] : 2
['T116', 'T122'] : 2
['T028', 'T114'] : 2
['T060', 'T062'] : 2
['T104', 'T122'] : 2
['T050', 'T191'] : 2
['T129', 'T131'] : 1
['T109', 'T192'] : 1
['T121', 'T129', 'T131'] : 1
['T104', 'T121'] : 1
['T109', 'T123', 'T130'] : 1
['T062', 'T170'] : 1
['T065', 'T066'] : 1
['T121', 'T131', 'T196'] : 1
['T122', 'T130'] : 1
['T114', 'T121', 'T127'] : 1
['T116', 'T123', 'T130'] : 1
['T114', 'T129'] : 1
['T114', 'T127'] : 1
['T114', 'T195'] : 1
['T114', 'T116'] : 1
['T057', 'T066'] : 1
['T065', 'T170'] : 1
['T116', 'T129', 'T131'] : 1
['T196', 'T197'] : 1
['T114', 'T116', 'T126'] : 1
['T114', 'T116', 'T121'] : 1
['T116', 'T121', 'T130'] : 1
['T109', 'T196'] : 1
['T131', 'T196', 'T197'] : 1
['T109', 'T129', 'T130'] : 1
['T130', 'T131', 'T197'] : 1
```


Name of each TUI listed in list above:
```
T092 : Organization
T062 : Research Activity
T170 : Intellectual Product
T066 : Machine Activity
T123 : Biologically Active Substance
T196 : Element, Ion, or Isotope
T050 : Experimental Model of Disease
T057 : Occupational Activity
T126 : Enzyme
T109 : Organic Chemical
T192 : Receptor
T203 : Drug Delivery Device
T130 : Indicator, Reagent, or Diagnostic Aid
T190 : Anatomical Abnormality
T093 : Health Care Related Organization
T065 : Educational Activity
T122 : Biomedical or Dental Material
T028 : Gene or Genome
T168 : Food
T125 : Hormone
T200 : Clinical Drug
T131 : Hazardous or Poisonous Substance
T129 : Immunologic Factor
T060 : Diagnostic Procedure
T197 : Inorganic Chemical
T019 : Congenital Abnormality
T127 : Vitamin
T121 : Pharmacologic Substance
T120 : Chemical Viewed Functionally
T025 : Cell
T195 : Antibiotic
T104 : Chemical Viewed Structurally
T047 : Disease or Syndrome
T114 : Nucleic Acid, Nucleoside, or Nucleotide
T073 : Manufactured Object
T059 : Laboratory Procedure
T191 : Neoplastic Process
T063 : Molecular Biology Research Technique
T116 : Amino Acid, Peptide, or Protein
```

Data above in table format (I also have it as a TSV):

Number | Frequency (#) | TUI 1 | Name 1 | TUI 2 | Name 2 | TUI 3 | Name 3 | TUI 4 | Name 4
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 4732 | T109 | Organic Chemical | T121 | Pharmacologic Substance |   |   |   |  
2 | 3980 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme |   |   |   |  
3 | 2485 | T123 | Biologically Active Substance | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
4 | 1903 | T116 | Amino Acid, Peptide, or Protein | T123 | Biologically Active Substance |   |   |   |  
5 | 930 | T121 | Pharmacologic Substance | T109 | Organic Chemical |   |   |   |  
6 | 669 | T116 | Amino Acid, Peptide, or Protein | T192 | Receptor |   |   |   |  
7 | 577 | T116 | Amino Acid, Peptide, or Protein | T129 | Immunologic Factor |   |   |   |  
8 | 516 | T129 | Immunologic Factor | T121 | Pharmacologic Substance |   |   |   |  
9 | 454 | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
10 | 283 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
11 | 246 | T121 | Pharmacologic Substance | T197 | Inorganic Chemical |   |   |   |  
12 | 221 | T073 | Manufactured Object | T093 | Health Care Related Organization |   |   |   |  
13 | 216 | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical |   |   |   |  
14 | 201 | T109 | Organic Chemical | T195 | Antibiotic |   |   |   |  
15 | 180 | T116 | Amino Acid, Peptide, or Protein | T121 | Pharmacologic Substance |   |   |   |  
16 | 171 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T123 | Biologically Active Substance |   |   |   |  
17 | 162 | T192 | Receptor | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
18 | 155 | T109 | Organic Chemical | T123 | Biologically Active Substance |   |   |   |  
19 | 147 | T123 | Biologically Active Substance | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |  
20 | 143 | T129 | Immunologic Factor | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |  
21 | 140 | T109 | Organic Chemical | T125 | Hormone | T121 | Pharmacologic Substance |   |  
22 | 132 | T109 | Organic Chemical | T131 | Hazardous or Poisonous Substance |   |   |   |  
23 | 122 | T116 | Amino Acid, Peptide, or Protein | T129 | Immunologic Factor | T121 | Pharmacologic Substance |   |  
24 | 118 | T109 | Organic Chemical | T127 | Vitamin | T121 | Pharmacologic Substance |   |  
25 | 97 | T125 | Hormone | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |  
26 | 87 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T192 | Receptor |   |  
27 | 83 | T121 | Pharmacologic Substance | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |  
28 | 81 | T121 | Pharmacologic Substance | T129 | Immunologic Factor |   |   |   |  
29 | 80 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme |   |  
30 | 79 | T109 | Organic Chemical | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
31 | 70 | T019 | Congenital Abnormality | T047 | Disease or Syndrome |   |   |   |  
32 | 69 | T116 | Amino Acid, Peptide, or Protein | T125 | Hormone | T121 | Pharmacologic Substance |   |  
33 | 68 | T116 | Amino Acid, Peptide, or Protein | T192 | Receptor | T129 | Immunologic Factor |   |  
34 | 68 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T121 | Pharmacologic Substance |   |   |   |  
35 | 65 | T126 | Enzyme | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
36 | 64 | T109 | Organic Chemical | T123 | Biologically Active Substance | T121 | Pharmacologic Substance |   |  
37 | 57 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |  
38 | 56 | T125 | Hormone | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
39 | 55 | T109 | Organic Chemical | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance |   |  
40 | 54 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T121 | Pharmacologic Substance |   |  
41 | 51 | T116 | Amino Acid, Peptide, or Protein | T123 | Biologically Active Substance | T121 | Pharmacologic Substance |   |  
42 | 49 | T195 | Antibiotic | T109 | Organic Chemical |   |   |   |  
43 | 47 | T116 | Amino Acid, Peptide, or Protein | T125 | Hormone |   |   |   |  
44 | 43 | T131 | Hazardous or Poisonous Substance | T109 | Organic Chemical |   |   |   |  
45 | 41 | T122 | Biomedical or Dental Material | T109 | Organic Chemical |   |   |   |  
46 | 39 | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein | T192 | Receptor |   |  
47 | 36 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T129 | Immunologic Factor |   |  
48 | 31 | T127 | Vitamin | T121 | Pharmacologic Substance |   |   |   |  
49 | 31 | T109 | Organic Chemical | T122 | Biomedical or Dental Material |   |   |   |  
50 | 29 | T109 | Organic Chemical | T129 | Immunologic Factor | T121 | Pharmacologic Substance |   |  
51 | 27 | T195 | Antibiotic | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
52 | 27 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance |   |   |   |  
53 | 26 | T073 | Manufactured Object | T170 | Intellectual Product |   |   |   |  
54 | 25 | T192 | Receptor | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein |   |  
55 | 24 | T109 | Organic Chemical | T125 | Hormone |   |   |   |  
56 | 21 | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical | T121 | Pharmacologic Substance |   |  
57 | 21 | T109 | Organic Chemical | T129 | Immunologic Factor |   |   |   |  
58 | 20 | T109 | Organic Chemical | T121 | Pharmacologic Substance | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
59 | 19 | T123 | Biologically Active Substance | T109 | Organic Chemical |   |   |   |  
60 | 18 | T200 | Clinical Drug | T203 | Drug Delivery Device |   |   |   |  
61 | 18 | T125 | Hormone | T121 | Pharmacologic Substance |   |   |   |  
62 | 17 | T196 | Element, Ion, or Isotope | T121 | Pharmacologic Substance |   |   |   |  
63 | 17 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T129 | Immunologic Factor |   |  
64 | 16 | T116 | Amino Acid, Peptide, or Protein | T195 | Antibiotic |   |   |   |  
65 | 15 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance | T109 | Organic Chemical |   |  
66 | 14 | T197 | Inorganic Chemical | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
67 | 14 | T192 | Receptor | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme |   |  
68 | 14 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T125 | Hormone |   |  
69 | 13 | T130 | Indicator, Reagent, or Diagnostic Aid | T121 | Pharmacologic Substance | T197 | Inorganic Chemical |   |  
70 | 13 | T121 | Pharmacologic Substance | T196 | Element, Ion, or Isotope |   |   |   |  
71 | 13 | T092 | Organization | T073 | Manufactured Object |   |   |   |  
72 | 12 | T168 | Food | T109 | Organic Chemical |   |   |   |  
73 | 12 | T123 | Biologically Active Substance | T196 | Element, Ion, or Isotope |   |   |   |  
74 | 12 | T121 | Pharmacologic Substance | T109 | Organic Chemical | T127 | Vitamin |   |  
75 | 11 | T197 | Inorganic Chemical | T122 | Biomedical or Dental Material |   |   |   |  
76 | 11 | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor | T121 | Pharmacologic Substance |   |  
77 | 10 | T130 | Indicator, Reagent, or Diagnostic Aid | T197 | Inorganic Chemical |   |   |   |  
78 | 10 | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor |   |   |   |  
79 | 10 | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme |   |  
80 | 10 | T121 | Pharmacologic Substance | T197 | Inorganic Chemical | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
81 | 9 | T131 | Hazardous or Poisonous Substance | T197 | Inorganic Chemical |   |   |   |  
82 | 9 | T131 | Hazardous or Poisonous Substance | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
83 | 9 | T130 | Indicator, Reagent, or Diagnostic Aid | T196 | Element, Ion, or Isotope |   |   |   |  
84 | 9 | T125 | Hormone | T121 | Pharmacologic Substance | T109 | Organic Chemical |   |  
85 | 9 | T123 | Biologically Active Substance | T131 | Hazardous or Poisonous Substance | T116 | Amino Acid, Peptide, or Protein |   |  
86 | 9 | T109 | Organic Chemical | T168 | Food |   |   |   |  
87 | 8 | T196 | Element, Ion, or Isotope | T131 | Hazardous or Poisonous Substance |   |   |   |  
88 | 8 | T196 | Element, Ion, or Isotope | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
89 | 8 | T196 | Element, Ion, or Isotope | T123 | Biologically Active Substance |   |   |   |  
90 | 8 | T123 | Biologically Active Substance | T131 | Hazardous or Poisonous Substance |   |   |   |  
91 | 8 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance | T196 | Element, Ion, or Isotope |   |  
92 | 8 | T122 | Biomedical or Dental Material | T197 | Inorganic Chemical |   |   |   |  
93 | 8 | T109 | Organic Chemical | T127 | Vitamin |   |   |   |  
94 | 8 | T059 | Laboratory Procedure | T063 | Molecular Biology Research Technique |   |   |   |  
95 | 7 | T197 | Inorganic Chemical | T131 | Hazardous or Poisonous Substance |   |   |   |  
96 | 7 | T127 | Vitamin | T121 | Pharmacologic Substance | T109 | Organic Chemical |   |  
97 | 7 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
98 | 7 | T121 | Pharmacologic Substance | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical |   |  
99 | 7 | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor |   |  
100 | 7 | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
101 | 7 | T093 | Health Care Related Organization | T073 | Manufactured Object |   |   |   |  
102 | 7 | T047 | Disease or Syndrome | T019 | Congenital Abnormality |   |   |   |  
103 | 6 | T203 | Drug Delivery Device | T200 | Clinical Drug |   |   |   |  
104 | 6 | T196 | Element, Ion, or Isotope | T123 | Biologically Active Substance | T121 | Pharmacologic Substance |   |  
105 | 6 | T130 | Indicator, Reagent, or Diagnostic Aid | T121 | Pharmacologic Substance |   |   |   |  
106 | 6 | T129 | Immunologic Factor | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
107 | 6 | T123 | Biologically Active Substance | T121 | Pharmacologic Substance | T197 | Inorganic Chemical |   |  
108 | 6 | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance | T109 | Organic Chemical |   |  
109 | 6 | T121 | Pharmacologic Substance | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
110 | 6 | T047 | Disease or Syndrome | T190 | Anatomical Abnormality |   |   |   |  
111 | 5 | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein |   |  
112 | 5 | T129 | Immunologic Factor | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
113 | 5 | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance |   |   |   |  
114 | 5 | T120 | Chemical Viewed Functionally | T109 | Organic Chemical |   |   |   |  
115 | 5 | T025 | Cell | T121 | Pharmacologic Substance |   |   |   |  
116 | 4 | T197 | Inorganic Chemical | T121 | Pharmacologic Substance |   |   |   |  
117 | 4 | T129 | Immunologic Factor | T121 | Pharmacologic Substance | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
118 | 4 | T121 | Pharmacologic Substance | T197 | Inorganic Chemical | T131 | Hazardous or Poisonous Substance |   |  
119 | 4 | T121 | Pharmacologic Substance | T109 | Organic Chemical | T125 | Hormone |   |  
120 | 4 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
121 | 4 | T116 | Amino Acid, Peptide, or Protein | T123 | Biologically Active Substance | T131 | Hazardous or Poisonous Substance |   |  
122 | 4 | T116 | Amino Acid, Peptide, or Protein | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance |   |  
123 | 4 | T116 | Amino Acid, Peptide, or Protein | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T123 | Biologically Active Substance |   |  
124 | 4 | T109 | Organic Chemical | T121 | Pharmacologic Substance | T168 | Food |   |  
125 | 3 | T196 | Element, Ion, or Isotope | T130 | Indicator, Reagent, or Diagnostic Aid | T121 | Pharmacologic Substance |   |  
126 | 3 | T170 | Intellectual Product | T060 | Diagnostic Procedure |   |   |   |  
127 | 3 | T168 | Food | T109 | Organic Chemical | T121 | Pharmacologic Substance |   |  
128 | 3 | T131 | Hazardous or Poisonous Substance | T196 | Element, Ion, or Isotope |   |   |   |  
129 | 3 | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical | T131 | Hazardous or Poisonous Substance |   |  
130 | 3 | T123 | Biologically Active Substance | T197 | Inorganic Chemical |   |   |   |  
131 | 3 | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance | T116 | Amino Acid, Peptide, or Protein |   |  
132 | 3 | T121 | Pharmacologic Substance | T127 | Vitamin |   |   |   |  
133 | 3 | T121 | Pharmacologic Substance | T109 | Organic Chemical | T129 | Immunologic Factor |   |  
134 | 3 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
135 | 3 | T109 | Organic Chemical | T123 | Biologically Active Substance | T131 | Hazardous or Poisonous Substance |   |  
136 | 2 | T190 | Anatomical Abnormality | T047 | Disease or Syndrome |   |   |   |  
137 | 2 | T131 | Hazardous or Poisonous Substance | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical |   |  
138 | 2 | T131 | Hazardous or Poisonous Substance | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme |   |  
139 | 2 | T127 | Vitamin | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |  
140 | 2 | T126 | Enzyme | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein |   |  
141 | 2 | T123 | Biologically Active Substance | T116 | Amino Acid, Peptide, or Protein | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
142 | 2 | T121 | Pharmacologic Substance | T196 | Element, Ion, or Isotope | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
143 | 2 | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance | T197 | Inorganic Chemical |   |  
144 | 2 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T123 | Biologically Active Substance |   |  
145 | 2 | T121 | Pharmacologic Substance | T025 | Cell |   |   |   |  
146 | 2 | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor | T121 | Pharmacologic Substance
147 | 2 | T116 | Amino Acid, Peptide, or Protein | T122 | Biomedical or Dental Material |   |   |   |  
148 | 2 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T123 | Biologically Active Substance | T121 | Pharmacologic Substance |   |  
149 | 2 | T109 | Organic Chemical | T131 | Hazardous or Poisonous Substance | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
150 | 2 | T104 | Chemical Viewed Structurally | T122 | Biomedical or Dental Material |   |   |   |  
151 | 2 | T073 | Manufactured Object | T092 | Organization |   |   |   |  
152 | 2 | T062 | Research Activity | T060 | Diagnostic Procedure |   |   |   |  
153 | 2 | T050 | Experimental Model of Disease | T191 | Neoplastic Process |   |   |   |  
154 | 1 | T197 | Inorganic Chemical | T196 | Element, Ion, or Isotope |   |   |   |  
155 | 1 | T196 | Element, Ion, or Isotope | T131 | Hazardous or Poisonous Substance | T197 | Inorganic Chemical |   |  
156 | 1 | T196 | Element, Ion, or Isotope | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance |   |  
157 | 1 | T196 | Element, Ion, or Isotope | T109 | Organic Chemical |   |   |   |  
158 | 1 | T195 | Antibiotic | T130 | Indicator, Reagent, or Diagnostic Aid | T109 | Organic Chemical |   |  
159 | 1 | T195 | Antibiotic | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |  
160 | 1 | T192 | Receptor | T109 | Organic Chemical |   |   |   |  
161 | 1 | T170 | Intellectual Product | T062 | Research Activity |   |   |   |  
162 | 1 | T131 | Hazardous or Poisonous Substance | T129 | Immunologic Factor |   |   |   |  
163 | 1 | T130 | Indicator, Reagent, or Diagnostic Aid | T197 | Inorganic Chemical | T131 | Hazardous or Poisonous Substance |   |  
164 | 1 | T130 | Indicator, Reagent, or Diagnostic Aid | T196 | Element, Ion, or Isotope | T121 | Pharmacologic Substance |   |  
165 | 1 | T130 | Indicator, Reagent, or Diagnostic Aid | T123 | Biologically Active Substance | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
166 | 1 | T130 | Indicator, Reagent, or Diagnostic Aid | T116 | Amino Acid, Peptide, or Protein |   |   |   |  
167 | 1 | T129 | Immunologic Factor | T131 | Hazardous or Poisonous Substance | T116 | Amino Acid, Peptide, or Protein |   |  
168 | 1 | T129 | Immunologic Factor | T121 | Pharmacologic Substance | T131 | Hazardous or Poisonous Substance |   |  
169 | 1 | T129 | Immunologic Factor | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid
170 | 1 | T129 | Immunologic Factor | T121 | Pharmacologic Substance | T109 | Organic Chemical |   |  
171 | 1 | T129 | Immunologic Factor | T109 | Organic Chemical |   |   |   |  
172 | 1 | T127 | Vitamin | T121 | Pharmacologic Substance | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
173 | 1 | T127 | Vitamin | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |  
174 | 1 | T127 | Vitamin | T109 | Organic Chemical |   |   |   |  
175 | 1 | T125 | Hormone | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
176 | 1 | T125 | Hormone | T109 | Organic Chemical |   |   |   |  
177 | 1 | T123 | Biologically Active Substance | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
178 | 1 | T122 | Biomedical or Dental Material | T130 | Indicator, Reagent, or Diagnostic Aid |   |   |   |  
179 | 1 | T121 | Pharmacologic Substance | T130 | Indicator, Reagent, or Diagnostic Aid | T196 | Element, Ion, or Isotope |   |  
180 | 1 | T121 | Pharmacologic Substance | T125 | Hormone |   |   |   |  
181 | 1 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid | T129 | Immunologic Factor
182 | 1 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
183 | 1 | T121 | Pharmacologic Substance | T116 | Amino Acid, Peptide, or Protein | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
184 | 1 | T121 | Pharmacologic Substance | T109 | Organic Chemical | T123 | Biologically Active Substance |   |  
185 | 1 | T116 | Amino Acid, Peptide, or Protein | T131 | Hazardous or Poisonous Substance |   |   |   |  
186 | 1 | T116 | Amino Acid, Peptide, or Protein | T130 | Indicator, Reagent, or Diagnostic Aid | T125 | Hormone |   |  
187 | 1 | T116 | Amino Acid, Peptide, or Protein | T127 | Vitamin | T121 | Pharmacologic Substance |   |  
188 | 1 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T131 | Hazardous or Poisonous Substance |   |  
189 | 1 | T116 | Amino Acid, Peptide, or Protein | T126 | Enzyme | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |  
190 | 1 | T116 | Amino Acid, Peptide, or Protein | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |  
191 | 1 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T130 | Indicator, Reagent, or Diagnostic Aid | T123 | Biologically Active Substance |   |  
192 | 1 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T129 | Immunologic Factor |   |   |   |  
193 | 1 | T114 | Nucleic Acid, Nucleoside, or Nucleotide | T028 | Gene or Genome |   |   |   |  
194 | 1 | T109 | Organic Chemical | T195 | Antibiotic | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
195 | 1 | T109 | Organic Chemical | T129 | Immunologic Factor | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
196 | 1 | T109 | Organic Chemical | T123 | Biologically Active Substance | T130 | Indicator, Reagent, or Diagnostic Aid |   |  
197 | 1 | T109 | Organic Chemical | T120 | Chemical Viewed Functionally |   |   |   |  
198 | 1 | T104 | Chemical Viewed Structurally | T121 | Pharmacologic Substance |   |   |   |  
199 | 1 | T065 | Educational Activity | T170 | Intellectual Product |   |   |   |  
200 | 1 | T065 | Educational Activity | T066 | Machine Activity |   |   |   |  
201 | 1 | T060 | Diagnostic Procedure | T170 | Intellectual Product |   |   |   |  
202 | 1 | T057 | Occupational Activity | T066 | Machine Activity |   |   |   |  
203 | 1 | T028 | Gene or Genome | T114 | Nucleic Acid, Nucleoside, or Nucleotide |   |   |   |

**Comment by ericawood** [comment]
For documentation purposes: I used the biolink model yaml file to develop this (below), no manual curation needed (still working on getting it into multi-ont-to-kg.py, but this looks good so far):

```
['T109---Organic Chemical', 'T121---Pharmacologic Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T123---Biologically Active Substance'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T192---Receptor'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T129---Immunologic Factor'] : molecular entity
['T121---Pharmacologic Substance', 'T129---Immunologic Factor'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance'] : molecular entity
['T121---Pharmacologic Substance', 'T197---Inorganic Chemical'] : chemical substance
['T073---Manufactured Object', 'T093---Health Care Related Organization'] : named thing
['T109---Organic Chemical', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T109---Organic Chemical', 'T195---Antibiotic'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T123---Biologically Active Substance'] : chemical substance
['T109---Organic Chemical', 'T123---Biologically Active Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T129---Immunologic Factor'] : molecular entity
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T125---Hormone'] : chemical substance
['T109---Organic Chemical', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T127---Vitamin'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T125---Hormone'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme', 'T192---Receptor'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T121---Pharmacologic Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T126---Enzyme'] : molecular entity
['T019---Congenital Abnormality', 'T047---Disease or Syndrome'] : disease
['T116---Amino Acid, Peptide, or Protein', 'T129---Immunologic Factor', 'T192---Receptor'] : molecular entity
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T123---Biologically Active Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T123---Biologically Active Substance'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T125---Hormone'] : molecular entity
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T109---Organic Chemical', 'T122---Biomedical or Dental Material'] : chemical substance
['T121---Pharmacologic Substance', 'T127---Vitamin'] : chemical substance
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T129---Immunologic Factor'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T195---Antibiotic'] : molecular entity
['T121---Pharmacologic Substance', 'T123---Biologically Active Substance'] : chemical substance
['T073---Manufactured Object', 'T170---Intellectual Product'] : named thing
['T109---Organic Chemical', 'T125---Hormone'] : chemical substance
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T109---Organic Chemical', 'T129---Immunologic Factor'] : chemical substance
['T200---Clinical Drug', 'T203---Drug Delivery Device'] : named thing
['T121---Pharmacologic Substance', 'T125---Hormone'] : chemical substance
['T121---Pharmacologic Substance', 'T196---Element, Ion, or Isotope'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme', 'T129---Immunologic Factor'] : molecular entity
['T130---Indicator, Reagent, or Diagnostic Aid', 'T197---Inorganic Chemical'] : chemical substance
['T121---Pharmacologic Substance', 'T130---Indicator, Reagent, or Diagnostic Aid', 'T197---Inorganic Chemical'] : chemical substance
['T073---Manufactured Object', 'T092---Organization'] : named thing
['T109---Organic Chemical', 'T168---Food'] : named thing
['T123---Biologically Active Substance', 'T196---Element, Ion, or Isotope'] : chemical substance
['T122---Biomedical or Dental Material', 'T197---Inorganic Chemical'] : chemical substance
['T121---Pharmacologic Substance', 'T129---Immunologic Factor', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T129---Immunologic Factor', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T131---Hazardous or Poisonous Substance', 'T197---Inorganic Chemical'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T131---Hazardous or Poisonous Substance'] : molecular entity
['T130---Indicator, Reagent, or Diagnostic Aid', 'T196---Element, Ion, or Isotope'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T123---Biologically Active Substance', 'T131---Hazardous or Poisonous Substance'] : molecular entity
['T131---Hazardous or Poisonous Substance', 'T196---Element, Ion, or Isotope'] : chemical substance
['T123---Biologically Active Substance', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T121---Pharmacologic Substance', 'T123---Biologically Active Substance', 'T196---Element, Ion, or Isotope'] : chemical substance
['T109---Organic Chemical', 'T127---Vitamin'] : chemical substance
['T059---Laboratory Procedure', 'T063---Molecular Biology Research Technique'] : procedure
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T121---Pharmacologic Substance', 'T123---Biologically Active Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T129---Immunologic Factor', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T121---Pharmacologic Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T121---Pharmacologic Substance', 'T123---Biologically Active Substance', 'T197---Inorganic Chemical'] : chemical substance
['T047---Disease or Syndrome', 'T190---Anatomical Abnormality'] : disease
['T121---Pharmacologic Substance', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T109---Organic Chemical', 'T120---Chemical Viewed Functionally'] : chemical substance
['T025---Cell', 'T121---Pharmacologic Substance'] : biological entity
['T121---Pharmacologic Substance', 'T131---Hazardous or Poisonous Substance', 'T197---Inorganic Chemical'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T131---Hazardous or Poisonous Substance'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T116---Amino Acid, Peptide, or Protein', 'T123---Biologically Active Substance'] : molecular entity
['T109---Organic Chemical', 'T121---Pharmacologic Substance', 'T168---Food'] : named thing
['T121---Pharmacologic Substance', 'T130---Indicator, Reagent, or Diagnostic Aid', 'T196---Element, Ion, or Isotope'] : chemical substance
['T060---Diagnostic Procedure', 'T170---Intellectual Product'] : named thing
['T109---Organic Chemical', 'T130---Indicator, Reagent, or Diagnostic Aid', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T123---Biologically Active Substance', 'T197---Inorganic Chemical'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T109---Organic Chemical', 'T123---Biologically Active Substance', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme', 'T131---Hazardous or Poisonous Substance'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T127---Vitamin'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T129---Immunologic Factor', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T122---Biomedical or Dental Material'] : molecular entity
['T104---Chemical Viewed Structurally', 'T122---Biomedical or Dental Material'] : chemical substance
['T060---Diagnostic Procedure', 'T062---Research Activity'] : procedure
['T050---Experimental Model of Disease', 'T191---Neoplastic Process'] : biological entity
['T196---Element, Ion, or Isotope', 'T197---Inorganic Chemical'] : chemical substance
['T131---Hazardous or Poisonous Substance', 'T196---Element, Ion, or Isotope', 'T197---Inorganic Chemical'] : chemical substance
['T121---Pharmacologic Substance', 'T131---Hazardous or Poisonous Substance', 'T196---Element, Ion, or Isotope'] : chemical substance
['T109---Organic Chemical', 'T196---Element, Ion, or Isotope'] : chemical substance
['T109---Organic Chemical', 'T130---Indicator, Reagent, or Diagnostic Aid', 'T195---Antibiotic'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T195---Antibiotic'] : chemical substance
['T109---Organic Chemical', 'T192---Receptor'] : chemical substance
['T062---Research Activity', 'T170---Intellectual Product'] : named thing
['T129---Immunologic Factor', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T130---Indicator, Reagent, or Diagnostic Aid', 'T131---Hazardous or Poisonous Substance', 'T197---Inorganic Chemical'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T123---Biologically Active Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T129---Immunologic Factor', 'T131---Hazardous or Poisonous Substance'] : molecular entity
['T121---Pharmacologic Substance', 'T129---Immunologic Factor', 'T131---Hazardous or Poisonous Substance'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T121---Pharmacologic Substance', 'T127---Vitamin'] : chemical substance
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T127---Vitamin'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T125---Hormone', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T116---Amino Acid, Peptide, or Protein', 'T123---Biologically Active Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T122---Biomedical or Dental Material', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T116---Amino Acid, Peptide, or Protein', 'T121---Pharmacologic Substance'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T116---Amino Acid, Peptide, or Protein', 'T126---Enzyme'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T116---Amino Acid, Peptide, or Protein'] : molecular entity
['T114---Nucleic Acid, Nucleoside, or Nucleotide', 'T129---Immunologic Factor'] : chemical substance
['T028---Gene or Genome', 'T114---Nucleic Acid, Nucleoside, or Nucleotide'] : molecular entity
['T109---Organic Chemical', 'T129---Immunologic Factor', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T109---Organic Chemical', 'T123---Biologically Active Substance', 'T130---Indicator, Reagent, or Diagnostic Aid'] : chemical substance
['T104---Chemical Viewed Structurally', 'T121---Pharmacologic Substance'] : chemical substance
['T065---Educational Activity', 'T170---Intellectual Product'] : named thing
['T065---Educational Activity', 'T066---Machine Activity'] : occurrent
['T057---Occupational Activity', 'T066---Machine Activity'] : activity and behavior
```

**Comment by ericawood** [comment]
Hi @saramsey, do you want it such that it always uses the category label derived from the TUIs to be the category label? On my testing with GO, the nodes with multiple TUIs always already have a category label (and from my understanding of your code, this will always be the case), so they don't actually get the one derived from the TUI. (I was following your standard on lines 602-603 of multi_ont_to_kg.py). Many of those derived from the TUIs and biolink model are less specific than the original category.

Example 1:
```
[https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/GO] Node http://purl.bioontology.org/ontology/GO/GO%3A0048086 has CUI with multiple associated TUIs: T039, T038 now has category named thing
Node curie: GO:0048086
TUI Category label: named thing
TUI list: ['T039', 'T038']
Category label of node: biological_process
```

Example 2:
```
[https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/GO] Node http://purl.bioontology.org/ontology/GO/GO%3A0061025 has CUI with multiple associated TUIs: T044, T043 now has category biological process or activity
Node curie: GO:0061025
TUI Category label: biological process or activity
TUI list: ['T044', 'T043']
Category label of node: biological_process
```

**Comment by saramsey** [comment]
Hi @ericawood, I'm glad you asked. 

I assume we are talking *only* about the logic in`multi_ont_to_json_kg.py`for dynamically determining the Biolink category of a node, right? (In the other KG JSON-building modules, I believe nodes' Biolink categories are kind of hard-coded, IIRC).

Having established that, I think that we will want to look at lines 589--604 of `multi_ont_to_json_kg.py`. 

<img width="1037" alt="Screen Shot 2020-08-27 at 11 56 30 AM" src="https://user-images.githubusercontent.com/5562107/91487892-51ccbd00-e863-11ea-9da7-c5156bc984c5.png">

The way I read this code, a node's TUI will only be used to ascertain the node's Biolink category if the following three conditions hold:

1. the node has a CUI associated with it, by a RDF `umls:has_cui` relationship
2. the node exactly one TUI associated with it, by a RDF `umls:has_tui` relationship
3. the node has no Biolink category that could be obtained by a previous call to `get_biolink_category_for_node` in the module `mult_ont_to_json_kg.py` (line 452)

I think we could modify the code at line 553, to handle the multi-TUI case and see if we can get a Biolink category for *each* of the TUIs. Accordingly, we could change the type of the variable `node_tui_category_label` to be `list`.  Then just after line 602, we could insert code to handle the case where there is more than one `node_tui_category_label` (i.e., new code to pick a category label).

**Comment by saramsey** [comment]
In Example 1 shown above, I am assuming that even `umls-go.ttl` contains the full ontology (i.e., `is_a` or `subclass_of` relationships between GO terms and their parent terms), and in that case, you are right, we already "know" the Biolink categories of most GO terms by the more reliable (and preferred) ontology-based approach (there may be a few exceptions which are typically deprecated GO terms). 

So, for your Examples 1--3, I think there would be no TUI-based reassignment of the node's Biolink category (see item 3 in my three-point list in the immediately preceding comment). 

But, for nodes like `UMLS:` or `MEDDRA:`, where we do not have a concept hierarchy, we definitely could make use of a TUI-based approach that can assign a Biolink category based on a combination of TUIs, based on a table of mappings that we have constructed by empirically analyzing multi-TUI frequency patterns in UMLS.

**Comment by ericawood** [comment]
Hi @saramsey,
Thank you for your response. I took a slightly different approach, as you can see in the (currently poorly documented) code below. Working back from the biolink category given to the TUI, it creates a path of ancestry, then compares those two paths to find the most specific ancestor. It also relies on the YAML file as downloaded in `build-multi-ont-kg.sh`. I could likely make it work better with the ontology dump instead, but it is currently designed to stand alone (primarily for my ease of testing). I will test using MEDDRA next.

![image](https://user-images.githubusercontent.com/36611732/91489784-38794000-e866-11ea-89bc-19b69dcabfbb.png)
![image](https://user-images.githubusercontent.com/36611732/91489838-5050c400-e866-11ea-8f38-faac537895e9.png)

Then, in an update to the code you included above.
![image](https://user-images.githubusercontent.com/36611732/91489993-9c036d80-e866-11ea-9aed-cb4c3d797590.png)

**Comment by saramsey** [comment]
Hi @ericawood, thank you for your reply.  Yes, I recall you explained this tree-walking idea. I think it sounds more appealing than compiling a mapping. Let's give it (your tree-walking method) a try. 

Just to be clear, the way I read your modifications to `make_nodes_dict_from_ontologies_list` (the last screencap that you attached), it appears that points (1) and (3) in my three-point list are still intact-- correct?  We would only be relaxing point (2) to include multi-TUI cases, right?

My reasoning: I don't think we want to *override* a Biolink category label that arises from the call to `get_biolink_category_for_node` on L452 (if that method call returns a category that we think is wrong, I think we should try to fix it in `curies-to-categories.yaml` ideally, or modify `curies-to-categories.yaml` so that it does L452 does not return a category for the node if for some reason it cannot be fixed to return what we think would be a correct category for a node.

**Comment by ericawood** [comment]
Hi @saramsey, yes points (1) and (3) are still intact. Thank you for your clarification regarding when to use the TUI category. I will test it on some other ontologies/ttl files to see when it works and how well it does that.

**Comment by saramsey** [comment]
Great!  Thank you, @ericawood! This is a big help in improving the quality of KG2.

**Comment by saramsey** [comment]
Oh, and for nodes with a `UMLS:` CURIE prefix, you are free to directly use the TUI to determine the Biolink category (see L672).

**Comment by ericawood** [comment]
When you say `umls` CURIE prefix, are you referring to the `UMLS` CURIE prefix? In kg2-simplified-report.json, I only see the `UMLS` CURIE prefix for nodes.

Proposed update:
![image](https://user-images.githubusercontent.com/36611732/91496609-45e7f780-e871-11ea-99fd-9cb37953ae5c.png)

**Comment by ericawood** [comment]
Commit 2bd4cc8fda5b2ccb3346b9813c065063f245ba3f should address this issue such that for nodes with more than one TUI that have no category label or have a UMLS prefix, the category label is the most specific common biolink category label ancestor of the TUIs. It has been tested on the TTL files/ontologies in the test ontology load inventory. 312 nodes got category labels through this system. It has yet to be tested on the full ontology load inventory.

**Comment by saramsey** [comment]
Confirmed. As expected, when Snakemake ran on `kg2steve`, on Aug 31 at 15:02 UTC, the script `multi_ont_to_json_kg.py` terminated with a `KeyError`:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1164, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 147, in make_kg2
    curie_to_uri_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 706, in make_nodes_dict_from_ontologies_list
    node_tui_category_label = get_category_for_multiple_tui(biolink_category_tree, node_tui_list, mappings_to_categories)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 445, in get_category_for_multiple_tui
    tui_categories.append(mappings_to_categories[tui])
KeyError: 'T091'
```
I have installed the latest `multi_ont_to_json_kg.py` script on `kg2steve`.

**Comment by saramsey** [comment]
When I ran `snakemake` with the dry-run option `-n`, the log file `build-kg2-snakemake.log` that was produced *seems* to have only the multi-ontology conversion step:
```
Job counts:
	count	jobs
	1	Finish
	1	Merge
	1	Nodes
	1	Ontologies_and_TTL
	1	Simplify
	1	Simplify_Nodes
	1	Simplify_Stats
	1	Slim
	1	Stats
	1	TSV
	10
```
I have saved the log file for posterity in `/home/ubuntu/build-kg2-snakemake.log-using-minus-n-save-for-erica`.

**Comment by saramsey** [comment]
Just started `build-kg2-snakemake.sh` on `kg2steve.rtx.ai` with the (snakemake) `-R Finish` option hard-coded into the script.

**Comment by kvarforl** [comment]
@saramsey  I'm unsure how to verify this fix for KG2.3.5. Could you document steps for me to follow here?

**Comment by ericawood** [comment]
@kvarforl 
This will require some rerunning. I would recommend forming a list of nodes using the fix and verifying in Neo4j that they are using their new category label. Please let me know if you have any further questions about this issue!

**Comment by saramsey** [comment]
@kvarforl I see that in the KG2.3.5 Neo4j database that you just set up, the node `GO:0048086` (which was referenced above in this issue as an example of the problem that we are trying to solve in #762) has a good, appropriate, and informative Biolink category label: `biological_process`:

<img width="428" alt="Screen Shot 2020-10-26 at 9 49 22 PM" src="https://user-images.githubusercontent.com/5562107/97258190-20299100-17d5-11eb-9178-b21094d5728c.png">

It is looking like maybe we can close this issue. Do you concur, @ericawood ?

**Comment by ericawood** [comment]
Hi @saramsey! The "GO" example above was not actually impacted by this issue, as it was falsely triggering the code block, which I fixed ("GO" nodes use the "build up to category of top node in the ontology" method). Most of the nodes impacted by this issue were "UMLS" prefixed nodes. Confidently verifying this fix would likely require going back into multi_ont_to_kg_json.py and recording which nodes trigger the fix, then making sure they match with Neo4j.

**Comment by kvarforl** [comment]
Okay I'm not sure I fully understand this issue and fix, but here is my stab at verifying it.

These are the only instances of the error message "Node ... has CUI  with multiple associated TUIS:... and could not be mapped." in  `build-kg2-ont-stderr.log`.
```
    13 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D000081362 has CUI with multipl       e associated TUIs: T091, T109 and could not be mapped
    14 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D011584 has CUI with multiple a       ssociated TUIs: T097, T091, T080, T041, T067 and could not be mapped
    15 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D016272 has CUI with multiple a       ssociated TUIs: T078, T091 and could not be mapped
    16 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D001696 has CUI with multiple a       ssociated TUIs: T091, T070 and could not be mapped
    17 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D001106 has CUI with multiple a       ssociated TUIs: T090, T091 and could not be mapped
    18 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D018559 has CUI with multiple a       ssociated TUIs: T091, T078 and could not be mapped
    19 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D018732 has CUI with multiple a       ssociated TUIs: T060, T091 and could not be mapped
    20 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D000073920 has CUI with multipl       e associated TUIs: T090, T091 and could not be mapped
    21 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D008490 has CUI with multiple a       ssociated TUIs: T091, T066 and could not be mapped
    22 [https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MSH] Node MESH:D010274 has CUI with multiple a       ssociated TUIs: T090, T091 and could not be mapped
```

In Neo4j, the above nodes all have the category_label  `named_thing`, which makes sense as I assume its the most ambiguous biolink term. The small number of these nodes seems good.

> Commit [2bd4cc8](https://github.com/RTXteam/RTX/commit/2bd4cc8fda5b2ccb3346b9813c065063f245ba3f) should address this issue such that for nodes with more than one TUI that have no category label or have a UMLS prefix, the category label is the most specific common biolink category label ancestor of the TUIs. It has been tested on the TTL files/ontologies in the test ontology load inventory. 312 nodes got category labels through this system. It has yet to be tested on the full ontology load inventory. If we find that this works, I will go back through and commit more comments describing what it is doing.

This comment led me to believe that UMLS nodes weren't being given specific biolink categorys, so I would assume that if the fix works, the overall percentage of UMLS nodes with the category_label `named_thing` would be lower in kg2.3.5 than it is in kg2.3.4. This is not the case: Kg2.3.5 UMLS nodes have ~4.1% category labels as `named_thing` and Kg2.3.4 UMLS nodes have ~2.1%. 

If this is a valid verification method, I would say it's probably not fixed. But again, I could easily be totally off base. Thoughts?

**Comment by saramsey** [comment]
For MONDO, out of 2292 nodes that have a category (in KG2.5.1) of `named thing`, all but 10 of them are obsolete nodes. And those 10 nodes I have fixed with commit 
10b666f .

**Comment by saramsey** [comment]
OK, we still have some work to do on this issue. For example, try this query:
```
match (n:`biolink:NamedThing` {provided_by: 'identifiers_org_registry:umls'}) return n.id, n.name, n.description limit 10;
```
<img width="917" alt="Screen Shot 2021-02-02 at 3 11 27 PM" src="https://user-images.githubusercontent.com/5562107/106674903-ef41c080-6568-11eb-9126-eec8fd42b852.png">

**Comment by ericawood** [comment]
This issue appears to be fixed in KG2.5.2. From `build-kg2-ont-stderr.log`:

![image](https://user-images.githubusercontent.com/36611732/110219610-3a573800-7e75-11eb-9129-bd60574e0cc7.png)
